blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/project-codeguard/rules/discussions
    about: Please ask and answer questions here.
  - name: Security Vulnerability Report
    url: https://github.com/project_codeguard/rules/security/policy
    about: Please report security vulnerabilities responsibly.
