---
name: Generate IDE Rules

on:
  push:
    branches:
      - main
    paths:
      - 'rules/**'
      - 'src/**'
      - 'pyproject.toml'
  workflow_dispatch:

jobs:
  generate-rules:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: uv sync

      - name: Generate IDE-specific rules
        run: uv run python src/unified_to_all.py rules/ .

      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n $(git status --porcelain ide_rules/) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push generated rules
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ide_rules/
          git commit -m "chore: regenerate IDE-specific rules"
          git push

